### ISSUE TITLE
client_rect does not get updated when the game window is resized

### ISSUE THREAD

**Issue by Cubesicle** [mfloob/egui-opengl-internal#2]
In app.rs:
```rust
let mut gui_thread_info = GUITHREADINFO {
    cbSize: std::mem::size_of::<GUITHREADINFO>() as u32,
    flags: GUITHREADINFO_FLAGS(0),
    hwndActive: HWND(0),
    hwndFocus: HWND(0),
    hwndCapture: HWND(0),
    hwndMenuOwner: HWND(0),
    hwndMoveSize: HWND(0),
    hwndCaret: HWND(0),
    rcCaret: RECT { left: 0, top: 0, right: 0, bottom: 0 },
};
unsafe { GetGUIThreadInfo(0, &mut gui_thread_info) };

if gui_thread_info.hwndMoveSize.0 > 0 {
    client_rect = self.get_client_rect();
}
```
`GetGUIThreadInfo` does not get the GUIThreadInfo of the game window. For some reason, it gets it from the window of the allocated console, so when I resize the console window, `client_rect` gets updated. However, when I remove `utils::alloc_console()` in the code from the example dll, it doesn't detect the game window being resized. Removing the window resize detection and calling `client_rect = self.get_client_rect();` outside of an if statement seems to fix it, but I don't know if that's the best solution.

**Comment by mfloob** [comment]
https://github.com/mfloob/egui-opengl-internal/pull/3 Thanks.
